### ISSUE TITLE
Multiple responses for same url is broken with v0.6.1

### ISSUE THREAD

**Issue by naveens** [getsentry/responses#167] opened 2017-08-08 09:11 UTC
```
$ cat /tmp/test.py 
import responses
import requests


@responses.activate
def test_my_api():
    with responses.RequestsMock(assert_all_requests_are_fired=True) as rsps:
        #import pdb; pdb.set_trace()
        rsps.add(responses.GET, 'http://twitter.com/api/1/foobar', status=500)
        rsps.add(responses.GET, 'http://twitter.com/api/1/foobar',
                 body='{}', status=200,
                 content_type='application/json')

        resp = requests.get('http://twitter.com/api/1/foobar')
        assert resp.status_code == 500
        resp = requests.get('http://twitter.com/api/1/foobar')
        assert resp.status_code == 200

test_my_api()

$ python /tmp/test.py 
Traceback (most recent call last):
  File "/tmp/test.py", line 19, in <module>
    test_my_api()
  File "<string>", line 3, in wrapper
  File "/tmp/test.py", line 17, in test_my_api
    assert resp.status_code == 200
AssertionError
```

**Comment by jakul** [comment] 2017-08-08 11:06
@dcramer This is a duplicate of #161  and can be closed. @naveens The fix for this is in the `master` branch.

**Closed** 2017-08-08 11:17 UTC
