### ISSUE TITLE
PyCharm warning: Cannot find some references

### ISSUE THREAD

**Issue by objque** [getsentry/responses#119] opened 2016-07-10 21:38 UTC
Hi,

I write my tests in PyCharm with responses 2.5.1 (python27) and pycharm highlights some objects of library such as method of request, activate method, add mock.

If I am run the tests, then all tests are performed successfully. But this highlights is distracting me.
Someone faced with it?

![image](https://cloud.githubusercontent.com/assets/7000585/16716228/39b26e36-46ff-11e6-9d94-6e638ea4500d.png)

**Comment by cyberbikepunk** [comment] 2016-07-15 12:37
I just started using responses today. i also use PyCharm. This is the same problem as #74 ... I recommend you disable the warning.

**Comment by cyberbikepunk** [comment] 2016-07-15 12:50
@objque or better: use the context manager. The imports are transparent and that means that you can jump to the class/function declarations with ctrl+B as usual.
```import responses
import requests


def test_my_api():
    with responses.RequestsMock() as rsps:
        rsps.add(responses.GET, 'http://twitter.com/api/1/foobar',
                 body='{}', status=200,
                 content_type='application/json')
        resp = requests.get('http://twitter.com/api/1/foobar')

        assert resp.status_code == 200

    # outside the context manager requests will hit the remote server
    resp = requests.get('http://twitter.com/api/1/foobar')
    resp.status_code == 404```

**Comment by ifedapoolarewaju** [comment] 2017-06-13 23:34
this is probably because `responses` [adds the module's functions at runtime](https://github.com/getsentry/responses/blob/master/responses.py#L314) and PyCharm is unable to detect them.

**Comment by Stevoisiak** [comment] 2018-05-14 14:17
@cyberbikepunk This resolves the warning for `@responses.activate`. However, there is still a warning for `responses.GET`.

**Comment by Stevoisiak** [comment] 2018-05-14 14:21
@cyberbikepunk's comment resolves warnings for `@responses.activate`, but PyCharm will still show a warning for `responses.GET`.

I recommend telling PyCharm to [suppress warnings](https://www.jetbrains.com/help/pycharm/suppressing-inspections.html#suppress-in-editor) for the `requests` module.

**Comment by gpkc** [comment] 2019-07-01 13:06
Actually @cyberbikepunk's comment also works with the `GET` stuff. Just use `rsps.GET`.

Also, this is a big deal for linters in general. Not only pycharm verification.

**Comment by pax0r** [comment] 2019-11-25 14:40
I think is caused by some dynamically built `__all__`. Responses could provide a pyi file for that (autobuilt on CI?) https://mypy.readthedocs.io/en/latest/stubs.html

**Comment by markstory** [comment] 2019-11-25 16:01
Closing this as 388a3c7 added explicit exports.

**Closed by markstory** 2019-11-25 16:01 UTC
