### ISSUE TITLE
one test .py can run successfully,but run the whole test folder,it report error

### ISSUE THREAD

**Issue by bainningking** [getsentry/responses#392] opened 2021-07-27 03:29 UTC
### Environment

I mock responses in django test, when i run one test.py it run ok,but when i run whole folder by pytest folder it not ok

the envitonment:
django==1.11.20
python==3.6.13
pytest==3.8.2
responses==0.13.3

### Steps to Reproduce
test_xx.py test_yy.py test_zz.py in tests folder
pytest test_xx.py ok
![image](https://user-images.githubusercontent.com/70629146/127090628-b452f210-4d2c-4bd6-a4d2-9774d9cba615.png)

pytest tests not ok

![image](https://user-images.githubusercontent.com/70629146/127090334-bc80214b-f453-459a-89ed-910bd4a3ba6c.png)

i don't why

**Comment by markstory** [comment] 2021-07-27 13:41
I don't either. Is there a way you could provide a reproduction of the problem you're seeing?

**Comment by beliaev-maksim** [comment] 2021-09-20 21:56
@markstory, @bainningking 
looks like tests are not isolated/dependent on each other.
also, from error message I see "not all requests have been executed", which you may see in [context manager](https://github.com/getsentry/responses#assertions-on-declared-responses)

@bainningking 
can you provide a snippet or a repo where we can reproduce, otherwise it is not possible to drill into the issue and then, we proceed to close the issue

**Comment by beliaev-maksim** [comment] 2022-01-19 14:48
@markstory 
please close this issue, not reproducible

**Closed** 2022-01-19 15:04 UTC
Labels: Status: Needs More Information
