### ISSUE TITLE
TypeError: cannot unpack non-iterable CallbackResponse object

### ISSUE THREAD

**Issue by philhoff-edeka** [getsentry/responses#358] opened 2020-11-12 13:04 UTC
After upgrading from responses `0.12.0` to `0.12.1` our unit tests fail with the following error:
```
...

../../../../venv/lib/python3.8/site-packages/requests/sessions.py:590: in post
    return self.request('POST', url, data=data, json=json, **kwargs)
../../../../venv/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py:515: in request
    return super(OAuth2Session, self).request(
../../../../venv/lib/python3.8/site-packages/aws_xray_sdk/ext/requests/patch.py:27: in _xray_traced_requests
    return xray_recorder.record_subsegment(
../../../../venv/lib/python3.8/site-packages/aws_xray_sdk/core/recorder.py:424: in record_subsegment
    return_value = wrapped(*args, **kwargs)
../../../../venv/lib/python3.8/site-packages/requests/sessions.py:542: in request
    resp = self.send(prep, **send_kwargs)
../../../../venv/lib/python3.8/site-packages/requests/sessions.py:655: in send
    r = adapter.send(request, **kwargs)
../../../../venv/lib/python3.8/site-packages/responses.py:733: in unbound_on_send
    return self._on_request(adapter, request, *a, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <responses.RequestsMock object at 0x104e06880>
adapter = <requests.adapters.HTTPAdapter object at 0x10a7a8a00>
request = <PreparedRequest [POST]>
kwargs = {'cert': None, 'proxies': OrderedDict(), 'stream': False, 'timeout': 10, ...}

    def _on_request(self, adapter, request, **kwargs):
>       match, match_failed_reasons = self._find_match(request)
E       TypeError: cannot unpack non-iterable CallbackResponse object

../../../../venv/lib/python3.8/site-packages/responses.py:680: TypeError
```

This seems to have been caused by the refactoring of the [`Response._find_match()`](https://github.com/getsentry/responses/compare/0.12.0...0.12.1?diff=split#diff-9cad42bd2062ffdacc3366b7281bb0b032dbea07a7af80f13765edfa295d2266R653-R677) method.

**Comment by laakejs** [comment] 2020-11-12 13:22
We have the same issue with a slightly different error message.

```
self = <responses.RequestsMock object at 0x7f1cb1ece7f0>
adapter = <requests.adapters.HTTPAdapter object at 0x7f1cba8af2b0>
request = <PreparedRequest [GET]>
kwargs = {'cert': None, 'proxies': OrderedDict(), 'stream': False, 'timeout': None, ...}
    def _on_request(self, adapter, request, **kwargs):
>       match, match_failed_reasons = self._find_match(request)
E       TypeError: 'Response' object is not iterable
/usr/local/lib/python3.6/site-packages/responses.py:680: TypeError
```

**Comment by hramezani** [comment] 2020-11-12 13:23
@philhoff-edeka @laakejs Could you please prepare a small test with the error?
This helps us to figure out the problem.

**Comment by laakejs** [comment] 2020-11-12 13:54
Hi @hramezani 
Here is a simplified Version of the test that is failing for us.
```
    @responses.activate
    def test_error(self, mocker):
        mocker.patch("mock_a_function", return_value="test")

        stage = "dev"
        responses.add(
            responses.GET,
            "https://someInternalApi",
            json={
                "items": [
                    {"id1": 123, "id2": 123},
                    {"id1": 123, "id2": 456},
                ],
                "last": True,
            },
            status=200,
        )
        # test id 123
        query_result_1 = query_api(
            id="123", stage=stage
        )
````

Further I found out that our test works with moto==1.3.14 bot fails with moto=1.3.16.

**Comment by hramezani** [comment] 2020-11-12 14:22
Thanks @laakejs, I couldn't reproduce the error with your example. Did you try to run your example locally? Did it throw `TypeError`?

**Comment by philhoff-edeka** [comment] 2020-11-12 14:32
@hramezani I've also tried to create a minimal example for you.
It passes on my machine when I use responses version 0.12.0 and fails when I upgrade to 0.12.1:

```python
# coding=utf-8
import responses
from requests_oauthlib import OAuth2Session


@responses.activate
def test_response():
    # given
    responses.add(
        method = responses.POST,
        url = "https://example.com/",
        body = "expected",
        status = 200
    )

    # when
    oauth_session = OAuth2Session()
    response = oauth_session.post(
        url = "https://example.com/",
        data = "actual"
    )

    # then
    assert len(responses.calls) == 1
    assert responses.calls[0].request.url == "https://example.com/"
    assert responses.calls[0].request.body == "actual"
    assert response.text == "expected"

```

**Comment by ypankovych** [comment] 2020-11-12 15:32
We're skipping the 0.12.1 version for now: `responses>=0.9.0,!=0.12.1` in the requirements.

**Comment by laakejs** [comment] 2020-11-12 15:44
The first error was on a python:3.6-slim Docker image.
On my local machine I have python3.7.5 installed. 
Locally our original test still fails (with another type error), but my minimal version (sry for the snipped, I just removed all the restricted content) runs as well as the example provided by @philhoff-edeka (I dont really get how this is possible).

from pip freeze:
```
requests==2.25.0
requests-oauthlib==1.3.0
responses==0.12.1
```

locally generated error:
```
env/lib/python3.7/site-packages/requests/api.py:76: in get
    return request('get', url, params=params, **kwargs)
env/lib/python3.7/site-packages/requests/api.py:61: in request
    return session.request(method=method, url=url, **kwargs)
env/lib/python3.7/site-packages/requests/sessions.py:542: in request
    resp = self.send(prep, **send_kwargs)
env/lib/python3.7/site-packages/requests/sessions.py:655: in send
    r = adapter.send(request, **kwargs)
env/lib/python3.7/site-packages/responses.py:733: in unbound_on_send
    return self._on_request(adapter, request, *a, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <responses.RequestsMock object at 0x7fbcf3c80950>, adapter = <requests.adapters.HTTPAdapter object at 0x7fbcf063c950>, request = <PreparedRequest [GET]>
kwargs = {'cert': None, 'proxies': OrderedDict(), 'stream': False, 'timeout': None, ...}

    def _on_request(self, adapter, request, **kwargs):
>       match, match_failed_reasons = self._find_match(request)
E       TypeError: cannot unpack non-iterable Response object

env/lib/python3.7/site-packages/responses.py:680: TypeError
```

**Comment by hramezani** [comment] 2020-11-12 15:48
@philhoff-edeka Thanks for the example.
I run your example in my machine with `python3.8` and `responses==0.12.1` and it runs without any problem.
Could you please give me other packages version like: `requests-oauthlib`, `requests`, `urllib3`

**Comment by philhoff-edeka** [comment] 2020-11-12 16:12
I'm using Python 3.8.1 and the following package versions:
`requests-oauthlib==1.3.0`
`requests==2.25.0`
`urllib3==1.25.10`

**Comment by hramezani** [comment] 2020-11-12 16:29
> I'm using Python 3.8.1 and the following package versions:
> `requests-oauthlib==1.3.0`
> `requests==2.25.0`
> `urllib3==1.25.10`

I tested your example with packaged versions provided by you and the example worked on my machine.
have you tried your example in your machine in a fresh env?

**Comment by philhoff-edeka** [comment] 2020-11-12 16:45
> I tested your example with packaged versions provided by you and the example worked on my machine.
> have you tried your example in your machine in a fresh env?

Yes, that's why I've reported this issue. Our CI/CD process broke and it always uses a fresh environment (and installs the latest and greatest dependencies).

**Comment by hramezani** [comment] 2020-11-12 16:53
> Yes, that's why I've reported this issue. Our CI/CD process broke and it always uses a fresh environment (and installs the latest and greatest dependencies).

But your example test works on a fresh env on my machine. So it seems you provided a wrong example and I couldn't reproduce it on my machine.
You have to provide a breaking example. Then I can check it and figure out the problem.
Thanks.

**Comment by hramezani** [comment] 2020-11-12 17:40
@philhoff-edeka, @laakejs I think you patched `requests` with another library and `responses` receive the patched result.
we had a change on `responses` to `Improve ConnectionError error message` in https://github.com/getsentry/responses/commit/cf3c5a685ae95bee1a714fd36cfb77d448a4b5ec 

@markstory I think the problem comes from then new `match_failed_reasons` which we introduce.  https://github.com/getsentry/responses/blob/30a7fa73e050b72432492e955faead2d37302fb6/responses.py#L680

We can change this function handle `match_failed_reasons` if it exists. What do you think?

**Comment by hramezani** [comment] 2020-11-12 20:51
I created a PR(https://github.com/getsentry/responses/pull/359) to address this problem.

**Comment by philhoff-edeka** [comment] 2020-11-13 06:56
Sounds plausible, we're also using moto extensively.
Thank you for digging deeper despite us not being able to provide a minimal example that works on your machine. 👍

**Comment by markstory** [comment] 2020-11-13 15:18
Why is `moto` mocking internals of `responses`?

**Comment by hramezani** [comment] 2020-11-13 15:25
> Why is `moto` mocking internals of `responses`?

I think they implement their own `_find_match` https://github.com/spulec/moto/blob/672a4b9a27f8c20324bc9f82bd94c051b24e7c16/moto/core/models.py#L267

I think `_find_match`  is internal of `responses` and we can change its behavior. Maybe they(`moto`) should fix this problem on their side.

Btw, I created a PR to fix it.(we can drop my PR if you think that they have to fix it)

**Comment by hramezani** [comment] 2020-11-13 16:27
There is an open PR on `moto` to fix the problem https://github.com/spulec/moto/pull/3466

**Comment by markstory** [comment] 2020-11-14 01:50
Closing as monkey patching internals of a library is fraught with peril and the problem lies with the patcher.

**Closed by markstory** 2020-11-14 01:50 UTC
