### ISSUE TITLE
0.17.0 blocks moto and httpretty interop

### ISSUE THREAD

**Issue by davetrollope** [getsentry/responses#467] opened 2022-01-11 21:33 UTC
We have tests that utilize httpretty and moto but the 0.17.0 update causes the following error:

requests.exceptions.ConnectionError: Connection refused by Responses - the call doesn't match any registered mock.

This is true because our internal calls are not an AWS destination and are mocked by httpretty.

Pinning back to 0.16.0 resolved the issue

```
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/responses/__init__.py", line 842, in unbound_on_send
    return self._on_request(adapter, request, *a, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/responses/__init__.py", line 821, in _on_request
    raise response
requests.exceptions.ConnectionError: Connection refused by Responses - the call doesn't match any registered mock.
```

**Comment by markstory** [comment] 2022-01-11 21:45
Are you using an pass through prefixes to exclude responses from attempting to handle specific requests?

**Comment by markstory** [comment] 2022-01-11 21:45
As a follow up is there a way to reproduce the failure you're having with 0.17 that passes with 0.16?

**Comment by bblommers** [comment] 2022-01-11 22:23
> Are you using an pass through prefixes to exclude responses from attempting to handle specific requests?

Moto maintainer here - yes, we do. This was our setup in 0.16:
```
responses_mock = responses.RequestsMock(assert_all_requests_are_fired=False)
responses_mock.add_passthru("http")
```

A reproducible usecase using Moto would be:
```
@moto.mock_sqs
def test_passthrough_requests():
    conn = boto3.client("sqs", region_name="us-west-1")
    conn.create_queue(QueueName="queue1")

    res = requests.get("https://httpbin.org/ip")
    assert res.status_code == 200
```
So the first request would be intercepted by `responses`, because our decorator has created a mock for it, but the second request should go through.

**Comment by bblommers** [comment] 2022-01-11 22:40
It looks like Moto was counting on the fact that `passthru_prefixes persisted across tests`, the bug that was fixed in this version.
We call `responses.reset()` every now and then, but we do not add the passthru-prefix back afterwards.

So as far as I can see this is an issue on Moto's side.

**Comment by beliaev-maksim** [comment] 2022-01-11 22:49
Hi @bblommers
That is true, I fixed that behaviour with passthru in #447


I think such implicit behaviour of passthru can cause lots of false positive tests.

If you need specific passthru everywhere, then I would consider using setUp method in test framework

Just let me know if we can somehow assist :)

**Comment by bblommers** [comment] 2022-01-12 14:09
@davetrollope Moto has just released a new version, 2.3.2.dev2, that works with all versions of `responses`.
If you do run into any other issues with the latest version, feel free to raise them in Moto's repo: https://github.com/spulec/moto/issues/4750

@beliaev-maksim Appreciate the offer! Looks like everything is sorted now. With 0.17.0, we no longer have to touch any of the internal API's, so that always a good sign :slightly_smiling_face: 

On a janitorial note: It looks like `ResponsesMock._matches` is no longer used anywhere: https://github.com/getsentry/responses/blob/6e7d4669c1a0bb236747111fc8e9502c281d7fcf/responses/__init__.py#L524
If you want, I can raise a PR to remove this field?

**Comment by beliaev-maksim** [comment] 2022-01-12 14:12
@bblommers 
right, this leaked via #456 when #416 has not yet merged

please go ahead and open a PR, thanks!

**Comment by davetrollope** [comment] 2022-01-12 14:44
Here is a simple test case that works on 0.16.0 but fails on 0.17.0 @markstory 
`import httpretty
import requests
import json
from moto import mock_s3

from unittest import TestCase


@httpretty.activate
class ResponsesTest(TestCase):

    TEST_URL = "http://testserver/foo/"

    def setUp(self):
        httpretty.enable
        httpretty.register_uri(httpretty.GET, self.TEST_URL,
                               body=json.dumps(['test']),
                               content_type='text/json',
                               status_code=200
                               )

    @mock_s3
    def test_moto_httpretty_interop(self):
        response = requests.get(self.TEST_URL)
        print(response)`

**Comment by beliaev-maksim** [comment] 2022-01-12 14:49
hi @davetrollope 
have you tried new version of `moto` as per https://github.com/getsentry/responses/issues/467#issuecomment-1011082580 ?

**Comment by davetrollope** [comment] 2022-01-18 14:25
@beliaev-maksim I installed moto 2.3.2 and the test case passes, but I am seeing other issues - probably related to updating moto too many versions without due consideration. From a responses perspective, you can close this ticket.

**Comment by beliaev-maksim** [comment] 2022-01-18 14:25
@davetrollope 
thanks for confirmation

@markstory 
please close

**Closed** 2022-01-18 15:09 UTC
Labels: bug, Status: Backlog
