### ISSUE TITLE
sleep in callback causes Not all requests have been executed AssertionError

### ISSUE THREAD

**Issue by LKajan** [getsentry/responses#309] opened 2020-03-11 13:11 UTC
When a sleep is added to the request callback to simulate a slow response AssertionError "Not all requests have been executed" is raised. Without this sleep on line 61 test passes.

I'm trying to test that my server is working as expected with slow responses from an api. E.g. requests are not blocking each other. There is a request sender thread for that.

Is this a bug or am I using *responses* or *pytest* in the wrong way? Suggestions how to make the test setup cleaner are also welcome :).

Responses: 0.10.12
Requests: 2.23.0

```python
import json
import threading
import time
from queue import Queue

import pytest
import requests
import responses


class ServerData:
    def __init__(self):
        self.received = []
        self.received_event = threading.Event()


class Sender(threading.Thread):
    def __init__(self, endpoint, queue, *args, **kwargs):
        kwargs['daemon'] = True
        super().__init__(*args, **kwargs)
        self.endpoint = endpoint
        self.queue = queue

    def run(self):
        while True:
            data = self.queue.get()
            requests.post(self.endpoint, data=json.dumps(data))


@pytest.fixture(scope='module')
def mocked_responses():
    with responses.RequestsMock() as rsps:
        yield rsps


class TestSlowHttpResponse:

    @pytest.fixture(scope='class')
    def endpoint(self):
        return 'http://localhost/api'

    @pytest.fixture(scope='class')
    def queue(self):
        return Queue()

    @pytest.fixture(scope='class', autouse=True)
    def request_sender(self, endpoint, queue, slow_handler):
        sender = Sender(endpoint, queue)
        sender.start()

    @pytest.fixture(scope='class')
    def server_data(self):
        return ServerData()

    @pytest.fixture(scope='class')
    def slow_handler(self, server_data, endpoint, mocked_responses):

        def request_handler(request):
            server_data.received.append(json.loads(request.body))
            server_data.received_event.set()
            time.sleep(2)

            return (201, {}, request.body)

        mocked_responses.add_callback(
            responses.POST,
            endpoint,
            callback=request_handler
        )

    @pytest.fixture(scope='class')
    def data(self):
        return {'foo': 'bar'}

    @pytest.fixture(scope='class', autouse=True)
    def send_data(self, queue, data):
        queue.put(data)

    @pytest.fixture
    def wait_server(self, server_data):
        server_data.received_event.wait(timeout=5)

    def test_server_received_data(self, server_data, data, wait_server):
        assert server_data.received[-1] == data

```

**Comment by markstory** [comment] 2020-03-11 13:24
You could use add_callback() to raise a timeout error instead of using sleep(). This would let you test the timeout failures without slowing down your test suite.

**Comment by LKajan** [comment] 2020-03-11 13:34
Thanks @markstory for your suggestion. I don't necessary want it to timeout just to be slow. Have you something on your mind in that case?

**Comment by markstory** [comment] 2020-03-12 01:46
Does being 'slow' trigger an exception or another problem in the system? If so then raise that error from your callback.

**Comment by LKajan** [comment] 2020-03-12 08:01
Our current implementation has a Process that publish data and multiple Reporters can be connected to listen those. Now when a request of one reporter stalls it blocks subsequent reporters. Before fixing that I wanted to write a test to confirm the blocking issue.

```python
# Our current process-reporter implementation
class Process():
    def __init__(self):
        self.reporters = []

    def add_reporter(self, reporter):
        self.reporters.append(reporter)

    def publish(self, data):
        for reporter in self.reporters:
            reporter.send(data)


class Reporter():
    def __init__(self, endpoint):
        self.endpoint = endpoint

    def send(self, data):
        requests.post(self.endpoint, data=data)


process = Process()
process.add_reporter(Reporter('http://foo.com/api'))
process.add_reporter(Reporter('http://bar.com/api'))
process.publish('report')
```

**Comment by markstory** [comment] 2020-03-15 03:25
Wouldn't a slow response/timeout trigger a subclass of `requests.exceptions.Timeout` then? Raising one of the timeout errors from a callback response would be how I approach this situation.

**Comment by beliaev-maksim** [comment] 2021-09-13 07:56
Hi @LKajan,
have you tried the suggestion with raising a `Timeout` ?

if that was helpful you can consider closing this issue

**Comment by LKajan** [comment] 2021-09-17 06:49
Thanks getting back to this.
I really wanted to test if my code worked well with slow responses that is caused by latency etc. That is mostly that requests are sent in own thread so waiting a response won't block the main thread. I was building an application that is used in a low bandwidth mobile connection so I have set timeout to really high.
I don't see how raising a Timeout would solve this when I want to receive a response.

If you see that sleeping in a response callback is not a valid use case and this library should not support that I'm ok to close this issue.

**Comment by beliaev-maksim** [comment] 2021-11-10 16:39
@LKajan 
callback with sleep should be valid

I tested following snippet and it worked. Can you provide a minimal snippet without `threading` and simplified?
need to ensure that issue is not caused by `threading` itself

~~~python
body = b"test callback"
status = 400
reason = "Bad Request"
headers = {
    "foo": "bar",
    "Content-Type": "application/json",
    "Content-Length": "13",
}
url = "http://example.com/"

def request_callback(_request):
    import time
    for i in range(10):
        time.sleep(1)
        print(i)
    return status, headers, body

@responses.activate
def test_sleep():
    responses.add_callback(responses.GET, url, request_callback)
    resp = requests.get(url)
    assert resp.text == "test callback"
    assert resp.status_code == status
    assert resp.reason == reason
    assert "bar" == resp.headers.get("foo")
    assert "application/json" == resp.headers.get("Content-Type")
    assert "13" == resp.headers.get("Content-Length")

~~~

with sleep
![image](https://user-images.githubusercontent.com/51964909/141154140-cd068cb3-29cb-4cec-8019-00808f00e8f2.png)

without sleep
![image](https://user-images.githubusercontent.com/51964909/141154222-0bb58523-390c-4246-94cb-0fe28bd02b6f.png)

**Comment by beliaev-maksim** [comment] 2022-01-07 18:50
@LKajan 
can you provide a self consistent snippet that causes issue?

see my example above, just sleep in callback works fine

**Comment by beliaev-maksim** [comment] 2022-02-23 09:35
@markstory 
there is no way to reproduce the issue and no provided minimal reproducible

I propose to close

**Closed** 2022-02-23 18:28 UTC
